const { clipboard, contextBridge, ipcRenderer } = require('electron');

function subscribe(channel, callback) {
  const listener = (_event, payload) => callback(payload);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
}

contextBridge.exposeInMainWorld('cliBridge', {
  getAppInfo: () => ipcRenderer.invoke('app:info'),
  getReleaseChangelog: (version) => ipcRenderer.invoke('app:release-changelog', version),
  getLatestReleaseStatus: (version, options) => ipcRenderer.invoke('app:latest-release-status', version, options),
  getSystemStats: () => ipcRenderer.invoke('app:system-stats'),
  getAppZoomFactor: () => ipcRenderer.invoke('app:get-zoom-factor'),
  setAppZoomFactor: (zoomFactor) => ipcRenderer.invoke('app:set-zoom-factor', zoomFactor),
  readUsageTracking: () => ipcRenderer.invoke('usage:read'),
  writeUsageRates: (rates) => ipcRenderer.invoke('usage:write-rates', rates),
  clearUsageRecords: () => ipcRenderer.invoke('usage:clear-records'),
  openWorkspacePath: (targetPath) => ipcRenderer.invoke('workspace:open-path', targetPath),
  openExternalUrl: (targetUrl) => ipcRenderer.invoke('workspace:open-url', targetUrl),
  openImageToolsPage: () => ipcRenderer.invoke('image-tools:open'),
  readWorkspaceTree: (options) => ipcRenderer.invoke('workspace:read-tree', options),
  readWorkspaceSkills: (options) => ipcRenderer.invoke('workspace:read-skills', options),
  chooseDirectory: () => ipcRenderer.invoke('dialog:choose-directory'),
  chooseTerminalExportDirectory: () => ipcRenderer.invoke('dialog:choose-export-directory'),
  readCodexConfig: (kind) => ipcRenderer.invoke('codex-config:read', kind),
  validateCodexConfig: (kind, content) => ipcRenderer.invoke('codex-config:validate', kind, content),
  writeCodexConfig: (kind, content) => ipcRenderer.invoke('codex-config:write', kind, content),
  listCodexConfigBackups: (kind) => ipcRenderer.invoke('codex-config:list-backups', kind),
  restoreCodexConfigBackup: (kind, backupName) => ipcRenderer.invoke('codex-config:restore-backup', kind, backupName),
  readCodexProfile: () => ipcRenderer.invoke('codex-config:read-profile'),
  writeCodexProfile: (profile) => ipcRenderer.invoke('codex-config:write-profile', profile),
  listCodexQuickProfiles: () => ipcRenderer.invoke('codex-config:list-quick-profiles'),
  saveCodexQuickProfile: (payload) => ipcRenderer.invoke('codex-config:save-quick-profile', payload),
  deleteCodexQuickProfile: (id) => ipcRenderer.invoke('codex-config:delete-quick-profile', id),
  openCodexConfigFolder: () => ipcRenderer.invoke('codex-config:open-folder'),
  readClaudeConfig: (kind) => ipcRenderer.invoke('claude-config:read', kind),
  validateClaudeConfig: (kind, content) => ipcRenderer.invoke('claude-config:validate', kind, content),
  writeClaudeConfig: (kind, content) => ipcRenderer.invoke('claude-config:write', kind, content),
  listClaudeConfigBackups: (kind) => ipcRenderer.invoke('claude-config:list-backups', kind),
  restoreClaudeConfigBackup: (kind, backupName) => ipcRenderer.invoke('claude-config:restore-backup', kind, backupName),
  readClaudeProfile: () => ipcRenderer.invoke('claude-config:read-profile'),
  writeClaudeProfile: (profile) => ipcRenderer.invoke('claude-config:write-profile', profile),
  listClaudeQuickProfiles: () => ipcRenderer.invoke('claude-config:list-quick-profiles'),
  saveClaudeQuickProfile: (payload) => ipcRenderer.invoke('claude-config:save-quick-profile', payload),
  deleteClaudeQuickProfile: (id) => ipcRenderer.invoke('claude-config:delete-quick-profile', id),
  openClaudeConfigFolder: () => ipcRenderer.invoke('claude-config:open-folder'),
  readClipboardText: () => clipboard.readText(),
  writeClipboardText: (text) => {
    clipboard.writeText(typeof text === 'string' ? text : '');
    return true;
  },
  saveCommandDockImage: (payload) => ipcRenderer.invoke('command-dock:save-image', payload),
  listQuickPrompts: () => ipcRenderer.invoke('quick-prompts:list'),
  saveQuickPrompt: (payload) => ipcRenderer.invoke('quick-prompts:save', payload),
  deleteQuickPrompt: (id) => ipcRenderer.invoke('quick-prompts:delete', id),
  listCommandPresets: () => ipcRenderer.invoke('command-presets:list'),
  saveCommandPreset: (payload) => ipcRenderer.invoke('command-presets:save', payload),
  selectCommandPreset: (id) => ipcRenderer.invoke('command-presets:select', id),
  deleteCommandPreset: (id) => ipcRenderer.invoke('command-presets:delete', id),
  saveAgentAvatar: (payload) => ipcRenderer.invoke('agents:save-avatar', payload),
  readImageApiConfig: () => ipcRenderer.invoke('image-api:read-config'),
  writeImageApiConfig: (payload) => ipcRenderer.invoke('image-api:write-config', payload),
  listImageGenerationHistory: () => ipcRenderer.invoke('image-api:list-history'),
  writeImageGenerationHistory: (payload) => ipcRenderer.invoke('image-api:write-history', payload),
  clearImageGenerationHistory: () => ipcRenderer.invoke('image-api:clear-history'),
  generateImage: (payload) => ipcRenderer.invoke('image-api:generate', payload),
  onImageGenerationTaskUpdate: (callback) => subscribe('image-api:task-update', callback),
  createTerminal: (options) => ipcRenderer.invoke('terminal:create', options),
  updateTerminalMeta: (id, patch) => ipcRenderer.invoke('terminal:update-meta', id, patch),
  killTerminal: (id) => ipcRenderer.invoke('terminal:kill', id),
  killAllTerminals: () => ipcRenderer.invoke('terminal:kill-all'),
  exportTerminal: (id, options) => ipcRenderer.invoke('terminal:export', id, options),
  writeTerminal: (id, data) => ipcRenderer.send('terminal:write', { id, data }),
  resizeTerminal: (id, cols, rows) => ipcRenderer.send('terminal:resize', { id, cols, rows }),
  onTerminalData: (callback) => subscribe('terminal:data', callback),
  onTerminalExit: (callback) => subscribe('terminal:exit', callback)
});
